### PR TITLE
Branch exceptions

### LINKED ISSUE #29: Add exceptions for flight list string parameter
Need to ensure that SkyControl asserts to show the FlightList as always true for the length of the string with accurate parameters if not it would fail/ throw error

### PR DESCRIPTION
**Pull request by Franky4566**
Add flight exceptions for 'add' operation to make code more defensive. fixes #29

### CODE REVIEW

File: src/main/java/seedu/duke/operationlist/FlightList.java [hunk 1]
```diff
@@ -99,14 +105,143 @@ private static boolean findAndRemoveFlight(String flightNumber) {
...
         }
         return isFlightFound;
     }
+
+    public void getNumberOfFlights() {
+        assert numOfFlights >= 0;
+        numOfFlights = flights.size();
+    }
+
+    public void getFlightDetails(String flightDetail) throws SkyControlException {
```
Comment (ivanthengwr) [inline src/main/java/seedu/duke/operationlist/FlightList.java:124]: Good use of slapping

File: src/main/java/seedu/duke/operationlist/FlightList.java [hunk 2]
```diff
@@ -3,64 +3,70 @@
...
+    public static String extractDetail(String command, String start, String end) throws SkyControlException {
+
         String extractedDetail;
-        if (end.equals("empty")) {
-            extractedDetail = command.substring(command.indexOf(start) + start.length());
-        } else {
-            extractedDetail = command.substring(command.indexOf(start) + start.length(), command.indexOf(end) - 1);
+        int startIndex = command.indexOf(start) + start.length();
+        int endIndex = command.lastIndexOf(end);
+        if (endIndex <= startIndex || endIndex < 0 || startIndex < 0) {
```
Comment (ivanthengwr) [inline src/main/java/seedu/duke/operationlist/FlightList.java:49]: Can replace the zeros with a constant variable to avoid magic numbers. Good use of Boolean logic. However, it would be good if you would encompass this logic into a single Boolean Logic. I.e. isEmptyDetail.

File: src/main/java/seedu/duke/operationlist/FlightList.java [hunk 3]
```diff
@@ -3,64 +3,70 @@
...
+            throw new SkyControlException(ui.getErrorMessage());
+        }
+        extractedDetail = command.substring(startIndex, endIndex).trim();
+        if (extractedDetail.equals(EMPTY_STRING)) {
```
Comment (ivanthengwr) [inline src/main/java/seedu/duke/operationlist/FlightList.java:53]: Similar to the above, can refractor into a single Boolean for easier identification

File: src/main/java/seedu/duke/operationlist/FlightList.java [hunk 4]
```diff
@@ -99,14 +105,143 @@ private static boolean findAndRemoveFlight(String flightNumber) {
         boolean isFlightFound = false;
         assert !flights.isEmpty();
         for (FlightInfo flight : flights) {
-            if (flight.getFlightNum().equals(flightNumber)) {
+            if (flight.getFlightNumber().equals(flightNumber)) {
```
Comment (ivanthengwr) [inline src/main/java/seedu/duke/operationlist/FlightList.java:108]: Similar to the above, can refractor into a single Boolean for easier identification

File: src/main/java/seedu/duke/operationlist/FlightList.java [hunk 5]
```diff
@@ -99,14 +105,143 @@ private static boolean findAndRemoveFlight(String flightNumber) {
...
+    }
+
+    private void validateDestinationLength(String destination) throws SkyControlException {
+        if (destination.length() > DESTINATION_LENGTH_LIMIT) {
+            throw new SkyControlException(ui.getExceedAirlineLengthError(destination));
+        }
+    }
+
+    private void validateTime(String time) throws SkyControlException {
+        String timeRegex = "([01]?[0-9]|2[0-3])[0-5][0-9]";
```
Comment (ivanthengwr) [inline src/main/java/seedu/duke/operationlist/FlightList.java:224]: Suggest putting it as a final constant variable.

**Review by ivanthengwr — APPROVED** [review]
Overall good job making the code more defensive, just a few minor refactoring and slap to be done. Good Job!
